# K8s_job_busybox.yml
# creates pod and assigns a volume to it
#

apiVersion: v1
kind: Pod
metadata:
  name: busybox-nfs
  namespace: default
spec:
  containers:
  - name: busybox
    image: busybox
    command:
      - "sleep"
      - "3600"
    volumeMounts:
      - mountPath: "/var/njo/pv" 
        name: mypv
    imagePullPolicy: IfNotPresent
  volumes:
    - name: mypv
      persistentVolumeClaim:
        claimName: nfs-pvc
