# k8s_nginx_daemonset.yml
#
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  labels:
    dset: nginx
spec:
  selector:
    matchLabels:
      dset: nginx
  template:
    metadata:
      labels:
        dset: nginx
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
