#k8s_pause2_0_deployment.yml
#
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: lots-of-nothing
spec:
  selector:
    matchLabels:
      app: pause
  replicas: 6
  template:
    metadata:
      labels:
        app: pause
    spec:
      containers:
      - name: pause
        image: k8s.gcr.io/pause:2.0

