# k8s_alpine_deployment.yml
#
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: alpine-deployment
spec:
  selector:
    matchLabels:
      app: alpine
      running: afterLables
  replicas: 3
  template:
    metadata:
      labels:
        app: alpine
        running: afterLables
    spec:
      containers:
      - name: alpine
        image: alpine
        command:
          - sleep 
          - "60"

