# k8s_alpine_pod.yml
# creates an alpine pod and sleeps for 3600 secs
#
apiVersion: v1
kind: Pod
metadata:
  name: busy2
  namespace: default
spec:
  containers:
  - name: busy2
    image: alpine
    command:
      - sleep
      - "30"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
